swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Earnmoney
host: petstore.swagger.io
basePath: /v2
tags:
  - name: user
    description: Operations about user
  - name: task
    description: Operations about task
schemes:
  - https
  - http
paths:
  /user/signup:
    post:
      tags:
        - user
      summary: Sign up a user
      description: This can only be done when user sign up.
      operationId: signupUser
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Sign up user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful operation
        '400':
          description: email/phone exists
          schema:
            type: string
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      produces:
        - application/xml
        - application/json
      parameters:
        - name: account
          in: query
          description: The user phone/email for login
          required: true
          type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid password
        '404':
          description: Not found account
definitions:
  User:
    type: object
    properties:
      uid:
        type: number
      email:
        type: string
      phone:
        type: string
      name:
        type: string
      password:
        type: string
      isOrganization:
        type: boolean
      coin:
        type: number
      realname:
        type: string
      birthYear:
        type: number
      gender:
        type: string
        enum:
          - male
          - female
          - other
      studentID:
        type: string
      address:
        type: string
    xml:
      name: User
  Task:
    type: object
    properties:
      tid:
        type: number
      title:
        type: string
      description:
        type: string
      startTime:
        type: string
        format: date-time
      endTime:
        type: string
        format: date-time
      reward:
        type: number
      coinPool:
        type: number
      numOfPeople:
        type: number
      participant:
        type: array
        items:
          type: number
      finisher:
        type: array
        items:
          type: number
      question:
        type: array
        items:
          type: object
          properties:
            isRequired:
              type: boolean
            questionType:
              type: string
              enum:
                - fill
                - single
                - multiple
            questionTitle:
              type: string
            option:
              type: array
              items:
                type: string
    xml:
      name: Task
  ApiResponse:
    type: object
    properties:
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
